### ISSUE TITLE
What should I do with my fork?

### ISSUE THREAD

**Issue by banacorn** [glennsl/bs-atom#1]
Out of need, I've forked this repo, tossed in a binding whenever I need one.
Now, I ended up with [hundreds of bindings in dozens of modules](https://github.com/banacorn/bs-atom).

I want to contribute these stuff back to this repo.
But I'm not sure if a huge PR would be a good idea.

The bindings are far from complete, and there are some design choices to be made (e.g. how to encode APIs with options), so I'm here asking for advice.

**Comment by glennsl** [comment]
Hey. Thanks for asking. And massive effort! I'd be fine with huge PR I think, if it's roughly backwards compatible at least.

Or if you want to keep maintaining it yourself I'd be happy to deprecate this and point people towards yours.

**Comment by banacorn** [comment]
I'll see if I can make it backwards compatible!

**Comment by banacorn** [comment]
@glennsl I think I'll keep maintaining it. Thank you for all of nice bindings you've created out there!

**Comment by glennsl** [comment]
Alright, cool. Do you want me to deprecate this and point people towards yours?

**Comment by banacorn** [comment]
Yes, thank you, that would be nice!
